### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by adamrt** [JustinMarshall98/Ganesha#43]
Hey great work. I have some PRs coming your way. 

One thing that is important though is that this code was not licensed under the GPL before you took over it. Did you get permission from the previous authors to re license all their years of code? If not, I think the GPL is invalid here (IANAL). Probably better to return his gomtuu's original license.txt. 

Just a thought.

**Comment by JustinMarshall98** [comment]
I had changed the license on the advice of someone else, if it is an issue I will make the change!

**Comment by adamrt** [comment]
Okay, no worries. I don't feel super strong about it. Nice work, thanks!
